# Generated by Django 5.2.8 on 2025-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_platform', models.CharField(choices=[('BOE', 'Boletín Oficial del Estado'), ('PCSP', 'Plataforma de Contratación del Sector Público'), ('ALL', 'All Sources')], db_index=True, default='ALL', max_length=50)),
                ('total_contracts', models.IntegerField(default=0)),
                ('published_contracts', models.IntegerField(default=0)),
                ('awarded_contracts', models.IntegerField(default=0)),
                ('in_progress_contracts', models.IntegerField(default=0)),
                ('completed_contracts', models.IntegerField(default=0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('works_count', models.IntegerField(default=0)),
                ('services_count', models.IntegerField(default=0)),
                ('supplies_count', models.IntegerField(default=0)),
                ('mixed_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('open_procedure_count', models.IntegerField(default=0)),
                ('restricted_procedure_count', models.IntegerField(default=0)),
                ('negotiated_procedure_count', models.IntegerField(default=0)),
                ('overpriced_count', models.IntegerField(default=0)),
                ('avg_overpricing_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_delay_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('high_delay_risk_count', models.IntegerField(default=0)),
                ('avg_corruption_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('high_corruption_risk_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Historical Snapshot',
                'verbose_name_plural': 'Historical Snapshots',
                'db_table': 'analytics_historical_snapshot',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date', 'source_platform'], name='analytics_h_snapsho_54b9d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trend_type', models.CharField(choices=[('OVERPRICING', 'Overpricing Trend'), ('DELAY', 'Delay Risk Trend'), ('CORRUPTION', 'Corruption Risk Trend'), ('BUDGET_GROWTH', 'Budget Growth Trend'), ('HIGH_RISK_INCREASE', 'High Risk Contract Increase')], max_length=30)),
                ('source_platform', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('UP', 'Increasing'), ('DOWN', 'Decreasing'), ('STABLE', 'Stable')], max_length=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('significance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('affected_contracts', models.IntegerField(default=0)),
                ('severity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'analytics_risk_trend',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['trend_type', 'start_date'], name='analytics_r_trend_t_c01761_idx')],
            },
        ),
    ]
