# Generated by Django 5.0.1 on 2025-11-26 14:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=300)),
                (
                    "tax_id",
                    models.CharField(
                        db_index=True, help_text="CIF/NIF", max_length=50, unique=True
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=300)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, db_index=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, db_index=True, max_length=200)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("total_contracts", models.IntegerField(default=0)),
                (
                    "total_awarded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "avg_contract_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of won bids",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                ("flag_reason", models.TextField(blank=True)),
                ("first_contract_date", models.DateField(blank=True, null=True)),
                ("last_contract_date", models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["-total_awarded_amount"],
                "indexes": [
                    models.Index(
                        fields=["region", "industry"], name="providers_p_region_c1023a_idx"
                    ),
                    models.Index(fields=["risk_score"], name="providers_p_risk_sc_9fcff1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("alert_type", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Alert",
                "verbose_name_plural": "Provider Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "is_resolved"], name="providers_p_severit_2270c4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("relationship_type", models.CharField(db_index=True, max_length=100)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence level in this relationship",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        default=dict, help_text="Evidence supporting this relationship"
                    ),
                ),
                (
                    "provider_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_a",
                        to="providers.provider",
                    ),
                ),
                (
                    "provider_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_b",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Relationship",
                "verbose_name_plural": "Provider Relationships",
                "unique_together": {("provider_a", "provider_b", "relationship_type")},
            },
        ),
    ]
