"""Provider models."""
from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.core.models import SoftDeleteModel


class Provider(SoftDeleteModel):
    """
    Company or supplier that participates in public contracts.

    Tracks company information and aggregated metrics
    for pattern analysis.
    """

    # Basic Information
    name = models.CharField(max_length=300, db_index=True)
    tax_id = models.CharField(max_length=50, unique=True, db_index=True, help_text="CIF/NIF")
    legal_name = models.CharField(max_length=300, blank=True)

    # Contact
    address = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    region = models.CharField(max_length=100, blank=True, db_index=True)
    postal_code = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    # Business Information
    industry = models.CharField(max_length=200, blank=True, db_index=True)
    company_size = models.CharField(max_length=50, blank=True)
    founded_year = models.IntegerField(null=True, blank=True)

    # Aggregated Metrics (updated by analytics)
    total_contracts = models.IntegerField(default=0)
    total_awarded_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    avg_contract_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    success_rate = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(Decimal("0")), MaxValueValidator(Decimal("100"))],
        help_text="Percentage of won bids",
    )

    # Risk Metrics
    risk_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(Decimal("0")), MaxValueValidator(Decimal("100"))],
    )
    is_flagged = models.BooleanField(default=False, db_index=True)
    flag_reason = models.TextField(blank=True)

    # Dates
    first_contract_date = models.DateField(null=True, blank=True)
    last_contract_date = models.DateField(null=True, blank=True, db_index=True)

    class Meta:
        verbose_name = "Provider"
        verbose_name_plural = "Providers"
        ordering = ["-total_awarded_amount"]
        indexes = [
            models.Index(fields=["region", "industry"]),
            models.Index(fields=["risk_score"]),
        ]

    def __str__(self) -> str:
        return f"{self.name} ({self.tax_id})"

    @property
    def has_high_risk(self) -> bool:
        """Check if provider has high risk score (>70)."""
        return self.risk_score and self.risk_score > 70

    @property
    def years_active(self) -> int | None:
        """Calculate years since first contract."""
        if self.first_contract_date:
            from datetime import date

            today = date.today()
            return today.year - self.first_contract_date.year
        return None


class ProviderRelationship(SoftDeleteModel):
    """
    Relationships between providers.

    Used to detect networks and potential shell companies.
    """

    provider_a = models.ForeignKey(
        Provider, on_delete=models.CASCADE, related_name="relationships_as_a"
    )
    provider_b = models.ForeignKey(
        Provider, on_delete=models.CASCADE, related_name="relationships_as_b"
    )
    relationship_type = models.CharField(max_length=100, db_index=True)
    confidence = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(Decimal("0")), MaxValueValidator(Decimal("100"))],
        help_text="Confidence level in this relationship",
    )
    evidence = models.JSONField(
        default=dict, help_text="Evidence supporting this relationship"
    )

    class Meta:
        verbose_name = "Provider Relationship"
        verbose_name_plural = "Provider Relationships"
        unique_together = [["provider_a", "provider_b", "relationship_type"]]

    def __str__(self) -> str:
        return f"{self.provider_a.name} <-> {self.provider_b.name}"


class ProviderAlert(SoftDeleteModel):
    """
    Alerts for suspicious provider behavior.

    Generated by the AI engine when patterns are detected.
    """

    SEVERITY_CHOICES = [
        ("LOW", "Low"),
        ("MEDIUM", "Medium"),
        ("HIGH", "High"),
        ("CRITICAL", "Critical"),
    ]

    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, related_name="alerts")
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, db_index=True)
    alert_type = models.CharField(max_length=100, db_index=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    evidence = models.JSONField(default=dict)

    # Status
    is_resolved = models.BooleanField(default=False, db_index=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolution_notes = models.TextField(blank=True)

    class Meta:
        verbose_name = "Provider Alert"
        verbose_name_plural = "Provider Alerts"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["severity", "is_resolved"]),
        ]

    def __str__(self) -> str:
        return f"{self.severity} - {self.title}"
