# Generated by Django 5.0.1 on 2025-11-26 14:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("WORKS", "Works"),
                            ("SERVICES", "Services"),
                            ("SUPPLIES", "Supplies"),
                            ("MIXED", "Mixed"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("IN_PROGRESS", "In Progress"),
                            ("AWARDED", "Awarded"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        db_index=True, decimal_places=2, help_text="Budget in EUR", max_digits=15
                    ),
                ),
                (
                    "awarded_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final awarded amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESTRICTED", "Restricted"),
                            ("NEGOTIATED", "Negotiated"),
                            ("COMPETITIVE_DIALOGUE", "Competitive Dialogue"),
                            ("MINOR", "Minor Contract"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, db_index=True, null=True)),
                ("deadline_date", models.DateField(blank=True, db_index=True, null=True)),
                ("award_date", models.DateField(blank=True, db_index=True, null=True)),
                ("contracting_authority", models.CharField(db_index=True, max_length=300)),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("province", models.CharField(blank=True, db_index=True, max_length=100)),
                ("municipality", models.CharField(blank=True, db_index=True, max_length=100)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("external_id", models.CharField(db_index=True, max_length=200, unique=True)),
                ("source_platform", models.CharField(db_index=True, max_length=100)),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall risk score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "corruption_risk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "delay_risk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "financial_risk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("is_overpriced", models.BooleanField(db_index=True, default=False)),
                ("has_amendments", models.BooleanField(default=False)),
                ("has_delays", models.BooleanField(default=False)),
                ("analyzed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("analysis_version", models.CharField(blank=True, max_length=20)),
                (
                    "awarded_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amendment_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("previous_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("amendment_date", models.DateField(db_index=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Amendment",
                "verbose_name_plural": "Contract Amendments",
                "ordering": ["-amendment_date"],
            },
        ),
        migrations.CreateModel(
            name="RawContractData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("source_platform", models.CharField(db_index=True, max_length=100)),
                ("external_id", models.CharField(db_index=True, max_length=200)),
                ("raw_data", models.JSONField()),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_data",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Contract Data",
                "verbose_name_plural": "Raw Contract Data",
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["status", "publication_date"], name="contracts_c_status_97cf41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["region", "contract_type"], name="contracts_c_region_25ef1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["risk_score"], name="contracts_c_risk_sc_b42eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="rawcontractdata",
            index=models.Index(
                fields=["is_processed", "created_at"], name="contracts_r_is_proc_e94dea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rawcontractdata",
            unique_together={("source_platform", "external_id")},
        ),
    ]
