# Generated by Django 5.2.8 on 2025-11-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
