# Generated by Django 5.0.1 on 2025-11-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="municipality",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="region",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
